[package]
name = "mullvadwaita"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
relm4 = { version = "0.6.0", features = ["libadwaita"] }
relm4-components = "0.6.0"
relm4-icons = { version = "0.6.0", features = ["refresh-large"] }
tracker = "*"
