[package]
name = "mullvadwaita"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
adw = { version = "*", optional = true, package = "libadwaita" }
gtk = { version = "*", package = "gtk4" }
relm4 = { version = "*", features = ["all"] }
relm4-components = "*"
relm4-icons = { version = "*", features = ["refresh-large"] }
tracker = "*"

futures = "*"
futures-util = "*"

tokio = { version = "*", features = ["rt-multi-thread", "full"] }
log = { version = "*", features = ["std", "max_level_trace"] }
simple_logger = "*"